# Generated by Django 3.2.3 on 2021-05-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_auto_20210527_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
